crawler:
  build: .
  links:
    - db
  ports:
    - "6060:6060"
  ulimits:
    nofile:
      hard: 25000
      soft: 25000


db:
  image: postgres
  environment:
    - POSTGRES_PASSWORD=centralised
    - POSTGRES_USER=alexander
    - POSTGRES_DB=btc
