crawler:
  build: .
  links:
    - db
  ulimits:
    nofile:
      hard: 16000
      soft: 16000


db:
  image: postgres
  environment:
    - POSTGRES_PASSWORD=centralised
    - POSTGRES_USER=alexander
    - POSTGRES_DB=btc
